repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt --all && git add -A'
        language: system
        types: [rust]
        pass_filenames: false
